# Generated by Django 5.1.1 on 2024-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
