# Generated by Django 5.1.1 on 2024-09-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_linemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.lineaccount'),
            preserve_default=False,
        ),
    ]
