# Generated by Django 5.1.1 on 2024-09-20 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_linemessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaccount',
            name='last_sent_date',
        ),
        migrations.AddField(
            model_name='linemessage',
            name='last_sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
